### PR TITLE
Pa 10 - search filters

### PR DESCRIPTION
**Pull request by novotnej**
includes user preferences if user is logged in

### CODE REVIEW

**Comment by hester-g** [comment]
looks good to me! for some reason im not sure that I have permission to merge this tho?

**Comment by novotnej** [comment]
You have to do the review process, then it should allow you to merge it

**Comment by hester-g** [comment]
although did you want the search and the grid to be integrated in this or will that be done separately @novotnej ?

**Comment by novotnej** [comment]
They should be integrated, aren't they?

**Review by hester-g — DISMISSED** [review]
yh looks good! - only q is the one commented prev, did you want to integrate the grid and the search in this branch, or do separately?

**Comment by hester-g** [comment]
only the list showed up for me, not the grid of pictures

**Comment by hester-g** [comment]
and i made sure to invalidate caches and have a clean build just make sure android studio wasn't messing anything up lol

**Comment by novotnej** [comment]
Ok weird, even if you clean build and reinstall the app? Because the list file shouldn't even be there iirc

**Comment by hester-g** [comment]
I'll try again, but I did do that

**Comment by novotnej** [comment]
I did a clean build and it should be there
Screen

**Comment by hester-g** [comment]
mine is still the dummy list? i'll have a better look in the morning im going to go to bed now lol

**Comment by novotnej** [comment]
Did you pull the latest version? Because that dummy list adapter file isn't even in there any more

https://github.com/novotnej/petmatch_android/tree/PA-10/app/src/main/java/uk/ac/bath/petmatch/Adapters

**Comment by hester-g** [comment]
okay i just realised I took myself off this, I thought I was just undoing my approval for a bit lol. so @Jabzilla or @avb49 please approve this, but @novotnej you were right I didn't have the latest version - bit confused why tho bc I don't think I've checked this branch out before. But anyway lol, the search works it looks sikk

**Comment by hester-g** [comment]
wait dw lol

**Review by hester-g — APPROVED** [review]
all good 👍

**Pull request merged**
